### PR TITLE
Upgrade to the latest core.async version

### PR DESCRIPTION
**Pull request by fredZen**
The core.async page seems to imply that 1.6.0 is the minimum clojure version
required, so I'm upgrading just to be on the safe side, although the tests do
pass with clojure 1.5.1.
Surprisingly, no upgrade to clojurescript seems to be necessary.

### CODE REVIEW

**Comment by fredZen** [comment]
I can see that some tests fail on travis https://travis-ci.org/weavejester/reagi/jobs/110781443 

I suspect there's something non deterministic about them (but maybe it's deterministic and just related to a precise version of the jdk). I will have a look into it but it might take some time.

**Comment by fredZen** [comment]
I'm pretty confident now that the test failures were not caused by the changes I introduced.

This failure is caused by a fairly straightforward race condition in the test (issue #13 - unfortunately I don't see a straightforward fix). It also happened in https://travis-ci.org/weavejester/reagi/jobs/28763280 and https://travis-ci.org/weavejester/reagi/jobs/28763279 , which were caused by simple changes to documentation.

```
FAIL in (test-join) (core_test.clj:466)
once
expected: (realized? j)
  actual: (not (realized? #<Events@2660a55c: 3>))
```

This failure is less obvious. GC's aren't very deterministic, but that's hand waving, not an explanation. However, I also saw this failure in https://travis-ci.org/weavejester/reagi/jobs/79782535 , which was caused by simple changes to documentation.

```
FAIL in (test-gc) (core_test.clj:385)
GC unreferenced streams
expected: (nil? (clojure.core/deref a))
  actual: (not (nil? 1))
```

**Comment by weavejester** [comment]
Yeah, I had forgotten but sometimes the tests aren't the most reliable, due to the library's asynchronous nature.

**Comment by weavejester** [comment]
This seems fine. Can you cut down the commit message to something like:

```
Update core.async dependency
```

**Pull request closed without merging**
