### PR TITLE
Add Pluggable interface and implementation

### PR DESCRIPTION
**Pull request by ul**
Sometimes I want this functionality, but I'm not sure that using it is right design decision. What do you think?

### CODE REVIEW

**Comment by weavejester** [comment]
Could you give an example of the situations in which you want this functionality?

**Comment by ul** [comment]
I am building the app where all state and communication encapsulated in the hub of event streams. There are some common event streams initialized at the start which play role of buses and I plug streams from modules later into them, sometimes through chain of map/filter/reduce etc. transformations.  I think this (event streams as buses allowing plug/unplug) is quite common case to include it to lib.

**Comment by weavejester** [comment]
The architecture you describe sounds more like CSP than FRP. In a CSP system, like core.async, channels are means of communication, and the idea of plugging into them dynamically makes perfect sense.

However, a FRP system is concerned about modelling values over time. Using an event stream as a communications bus doesn't fit this paradigm, because it doesn't represent a changing value.

Could you describe the problem you're trying to solve?

**Comment by ul** [comment]
One of projects where I am using reagi is about BCI (Brain-Computer Interface). I've coded my system in rather reactive way (I think so) — e. g. there is flow of datagrams from BCI driver which I push into event stream, use 'map' to do some DSP on it, classifier also goes as map over latter one, and this stream also is plotted in GUI — all is about dataflow. Everything does not need plug/unplug if I describe every source and transformations at app start. But I have dynamically plugged/unplugged EEG modules and modules of controlled devices. And it is convenient to unplug previous source of e. g. eeg signal from this reactive network and plug another. In general this could be done by changing source which pushes to event stream, not event stream connections. But there is also one more use case, when I define streams at first and later connect them defining topology of dataflow — plug/unplug ideal for it.

**Comment by weavejester** [comment]
It sounds like the [core.async/mix](https://github.com/clojure/core.async/blob/master/src/main/clojure/clojure/core/async.clj#L704) function might be what you're looking for. Since Reagi is built on top of core.async, it doesn't attempt to reproduce the low-level control that core.async provides.

In your case, I'd suggest doing something like:

``` clojure
(let [ch (async/chan)]
  (def input-mixer (async/mix ch))
  (def input-events (r/events ch)))
```

You can add and remove inputs from the input mixer using `admix` and `unmix`, while the input event stream remains functional.

(Disclaimer: I haven't actually used async/mix in a real project, so I might be wrong!)

**Comment by ul** [comment]
Thanks for advice, I'll try this way!

**Pull request closed without merging**
